project:
  type: website

website:
  title: "Vast-Challenge-2026"
  navbar:
    left:
    - text: "Proposal"
      href: "proposal.qmd"
    - text: "Methodology"
      menu:
      - text: "Data Preparation"
        href: "dataprep.qmd"
      - text: "Statistical Analysis"
        href: "analysis.qmd"
      - text: "Visualisation"
        href: "visual.qmd"
    - text: "Meeting Minutes"
      href: "meeting_minutes.qmd"
    right:
    - text: "The Team"
      href: "team.qmd"

format:
  html:
    embed-resources: true
    theme: minty
    css: styles.css
    toc: true

editor: visual

