project:
  type: website

website:
  title: "Vast-Challenge-2026"
  navbar:
    left:
    - text: "Proposal"
      href: "proposal.qmd"
    - text: "Meeting Minutes"
      href: "meeting_minutes.qmd"
    right:
    - text: "The Team"
      href: "team.qmd"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

