project:
  type: website

website:
  title: "BreachLens"
  navbar:
    left:
    - text: "Proposal"
      href: "proposal.qmd"
    - text: "Methodology"
      menu:
      - text: "Data Preparation"
        href: "Methodology/dataprep.qmd"
      - text: "Analysis"
        href: "Methodology/analysis.qmd"
    - text: "Findings"
      href: "finding.qmd"
    - text: "Poster"
      href: "poster.qmd"
    - text: "Meeting Minutes"
      href: "meeting_minutes.qmd"
    right:
    - text: "Shiny App"
      menu:
      - text: "User Guide"
        href: "ShinyApp/guide.qmd"
      - text: "Shiny App"
        href: "https://kaykhaing.shinyapps.io/BreachLens/"
    - text: "The Team"
      href: "team.qmd"

format:
  html:
    embed-resources: true
    theme: litera
    css: styles.css
    toc: true
    include-in-header:
      text: |
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400;500;600&family=Space+Grotesk:wght@400;500;600;700&family=Spline+Sans:wght@400;500;600;700&display=swap" rel="stylesheet">

editor: visual

